config/routes.rb
Rails.application.routes.draw do
  resources :chapters
  resources :users
  resources :cartoons
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main', to: 'main#main'
  get 'genre', to: 'main#genre'
  get 'cartoon', to: 'main#allcartoons'

  get 'sign_up', to: 'registration#new'
  post 'sign_up', to: 'registration#create'

  get 'login', to: 'session#new'
  post 'login', to: 'session#create'

  get 'admin/update/cartoon', to: 'main#update'
  post 'admin/update/cartoon', to: 'main#update'

  delete 'logout', to: 'session#destroy'

  get 'search', to: 'main#search'

  get ":name" , to:"main#cartoon"
  get ":name/:chapter" , to:"main#chapter"

  post 'comments', to: "comments#create"
  post '/cartoon/:name/follow', to: "follow#follow", as: "follow_cartoon"
  post '/cartoon/:name/unfollow', to: "follow#unfollow", as: "unfollow_cartoon"
end

app/models/cartoon.rb
class Cartoon < ApplicationRecord
	TAGS = Genre.all
	DAY = %i[sunday monday tuesday wednesday thursday friday saturday]
	has_many :chapters , dependent: :destroy
	has_one_attached :image

	has_many :follows
	has_many :users, through: :follows
end

app/controllers/cartoons_controller.rb
class CartoonsController < ApplicationController
  before_action :set_cartoon, only: %i[ show edit update destroy ]

  # GET /cartoons or /cartoons.json
  def index
    @cartoons = Cartoon.all
  end

  # GET /cartoons/1 or /cartoons/1.json
  def show
  end

  # GET /cartoons/new
  def new
    @cartoon = Cartoon.new
  end

  # GET /cartoons/1/edit
  def edit
  end

  # POST /cartoons or /cartoons.json
  def create
    @cartoon = Cartoon.new(cartoon_params)

    respond_to do |format|
      if @cartoon.save
        format.html { redirect_to @cartoon, notice: "Cartoon was successfully created." }
        format.json { render :show, status: :created, location: @cartoon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cartoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartoons/1 or /cartoons/1.json
  def update
    respond_to do |format|
      if @cartoon.update(cartoon_params)
        format.html { redirect_to @cartoon, notice: "Cartoon was successfully updated." }
        format.json { render :show, status: :ok, location: @cartoon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cartoon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartoons/1 or /cartoons/1.json
  def destroy
    @cartoon.destroy
    respond_to do |format|
      format.html { redirect_to cartoons_url, notice: "Cartoon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartoon
      @cartoon = Cartoon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cartoon_params
      params.require(:cartoon).permit(:name, :status, :writer, :shortinfo, :daytoupdate , :image ,tags:[] )
    end
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/views/cartoons/_form.html.erb
<%= form_with(model: cartoon) do |form| %>
  <% if cartoon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cartoon.errors.count, "error") %> prohibited this cartoon from being saved:</h2>

      <ul>
        <% cartoon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ["continue","complete"]%>
  </div>

  <div class="field">
    <%= form.label :writer %>
    <%= form.text_field :writer %>
  </div>

  <div class="field">
    <%= form.label :shortinfo %>
    <%= form.text_field :shortinfo %>
  </div>

  <h5>TAGS</h5>
  <% Cartoon::TAGS.each do |key| %>
    
    <%= form.check_box :tags, { multiple: true, checked: form.object.tags&.include?(key.name.to_s) }, key.name, nil %>
    <%= form.label key.name %>
  <% end %>

  <div class="field">
    <%= form.label :daytoupdate %>
    <%= form.select :daytoupdate, ["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]%>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cartoons/edit.html.erb
<h1>Editing Cartoon</h1>

<%= render 'form', cartoon: @cartoon %>

<%= link_to 'Show', @cartoon %> |
<%= link_to 'Back', cartoons_path %>

app/views/cartoons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cartoons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Writer</th>
      <th>Shortinfo</th>
      <th>Tags</th>
      <th>Daytoupdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartoons.each do |cartoon| %>
      <tr>
        <td><%= cartoon.name %></td>
        <td><%= cartoon.status %></td>
        <td><%= cartoon.writer %></td>
        <td><%= cartoon.shortinfo %></td>
        <td><%= cartoon.tags.to_sentence %></td>
        <td><%= cartoon.daytoupdate %></td>
        <td><%= link_to 'Show', cartoon %></td>
        <td><%= link_to 'Edit', edit_cartoon_path(cartoon) %></td>
        <td><%= link_to 'Destroy', cartoon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartoon', new_cartoon_path %>

app/views/cartoons/new.html.erb
<h1>New Cartoon</h1>

<%= render 'form', cartoon: @cartoon %>

app/views/cartoons/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@cartoon.image , style:'width:200px ; height:200px')%>
<p>
  <strong>Name:</strong>
  <%= @cartoon.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @cartoon.status %>
</p>

<p>
  <strong>Writer:</strong>
  <%= @cartoon.writer %>
</p>

<p>
  <strong>Shortinfo:</strong>
  <%= @cartoon.shortinfo %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @cartoon.tags.to_sentence %>
</p>

<p>
  <strong>Daytoupdate:</strong>
  <%= @cartoon.daytoupdate %>
</p>