config/routes.rb
Rails.application.routes.draw do
  resources :chapters
  resources :users
  resources :cartoons
  resources :genres
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'main', to: 'main#main'
  get 'genre', to: 'main#genre'
  get 'cartoon', to: 'main#allcartoons'

  get 'sign_up', to: 'registration#new'
  post 'sign_up', to: 'registration#create'

  get 'login', to: 'session#new'
  post 'login', to: 'session#create'

  get 'admin/update/cartoon', to: 'main#update'
  post 'admin/update/cartoon', to: 'main#update'

  delete 'logout', to: 'session#destroy'

  get 'search', to: 'main#search'

  get ":name" , to:"main#cartoon"
  get ":name/:chapter" , to:"main#chapter"

  post 'comments', to: "comments#create"
  post '/cartoon/:name/follow', to: "follow#follow", as: "follow_cartoon"
  post '/cartoon/:name/unfollow', to: "follow#unfollow", as: "unfollow_cartoon"
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :cartoon
  has_many_attached :images
  has_many :comments, dependent: :destroy
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: %i[ show edit update destroy ]

  # GET /chapters or /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1 or /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters or /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: "Chapter was successfully created." }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1 or /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: "Chapter was successfully updated." }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1 or /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: "Chapter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chapter_params
      params.require(:chapter).permit(:num, :cartoon_id ,images: [])
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= form_with(model: chapter) do |form| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
        <% chapter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :num %>
    <%= form.number_field :num %>
  </div>

  <div class="field">
    <%= form.label :cartoon_id %>
    <%= form.collection_select(:cartoon_id, Cartoon.all, :id, :name) %>
  </div>

   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :images , multiple:true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chapters</h1>

<table>
  <thead>
    <tr>
      <th>Num</th>
      <th>Cartoon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.num %></td>
        <td><%= chapter.cartoon.name %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num:</strong>
  <%= @chapter.num %>
</p>

<p>
  <strong>Cartoon:</strong>
  <%= @chapter.cartoon.name %>
</p>

<% @chapter.images.each do |image| %>
  <%= image_tag(image,style: 'height: 200px; width: 200px; display: block;' ) %>
<% end %>